module.exports = {
  ESTIMATE_NOT_FOUND: "ESTIMATE_NOT_FOUND",
  ESTIMATE_NOT_APPROVED: "ESTIMATE_NOT_APPROVED",
  QUOTE_ALREADY_EXISTS: "QUOTE_ALREADY_EXISTS",
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  // Adaugă la obiectul existent
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  QUOTE_NOT_APPROVED: "QUOTE_NOT_APPROVED",
  INVOICE_CANCELED_CANNOT_SEND: "INVOICE_CANCELED_CANNOT_SEND",
  INVOICE_NO_CLIENT_EMAIL: "INVOICE_NO_CLIENT_EMAIL",
  SMTP_NOT_CONFIGURED: "SMTP_NOT_CONFIGURED",
  INVOICE_CANCELED_CANNOT_PAY: "INVOICE_CANCELED_CANNOT_PAY",
  INVALID_PAYMENT_AMOUNT: "INVALID_PAYMENT_AMOUNT",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  INVALID_REPORT_TYPE: "INVALID_REPORT_TYPE",
  REPORT_DELETE_FORBIDDEN: "REPORT_DELETE_FORBIDDEN",

  // Clients
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  CLIENT_EMAIL_ALREADY_EXISTS: "CLIENT_EMAIL_ALREADY_EXISTS",

  // Projects
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_NAME_AND_CLIENT_REQUIRED: "PROJECT_NAME_AND_CLIENT_REQUIRED",

  // Estimating
  ESTIMATE_TITLE_REQUIRED: "ESTIMATE_TITLE_REQUIRED",
  ESTIMATE_INVALID_CLIENT: "ESTIMATE_INVALID_CLIENT",
  ESTIMATE_INVALID_STATUS: "ESTIMATE_INVALID_STATUS",
  ESTIMATE_NO_ITEMS: "ESTIMATE_NO_ITEMS",
  ESTIMATE_ITEM_DESCRIPTION_REQUIRED: "ESTIMATE_ITEM_DESCRIPTION_REQUIRED",
  ESTIMATE_ITEM_QUANTITY_INVALID: "ESTIMATE_ITEM_QUANTITY_INVALID",
  ESTIMATE_ITEM_UNIT_COST_INVALID: "ESTIMATE_ITEM_UNIT_COST_INVALID",
  ESTIMATE_ITEM_MARGIN_INVALID: "ESTIMATE_ITEM_MARGIN_INVALID",
  ESTIMATE_UPDATE_NOT_FOUND: "ESTIMATE_UPDATE_NOT_FOUND",
  ESTIMATE_ALREADY_ARCHIVED: "ESTIMATE_ALREADY_ARCHIVED",

  // Materials
  MATERIAL_NOT_FOUND: "MATERIAL_NOT_FOUND",
  MATERIAL_CODE_ALREADY_EXISTS: "MATERIAL_CODE_ALREADY_EXISTS",

  // Invoices (business-rule transitions not yet covered by INVALID_STATUS_TRANSITION)
  INVOICE_CANCELED_LOCKED: "INVOICE_CANCELED_LOCKED",
  INVOICE_PAID_TO_DRAFT_FORBIDDEN: "INVOICE_PAID_TO_DRAFT_FORBIDDEN",

  // Coduri de succes (reutilizate cross-modul unde frontend-ul depinde azi de
  // `message`-ul brut al backend-ului pentru textul de succes afișat) — vezi
  // authCodes.js pentru precedentul deja stabilit (succes + eroare în aceeași
  // taxonomie, per domeniu).
  QUOTE_DELETED: "QUOTE_DELETED",
  ALL_QUOTES_DELETED: "ALL_QUOTES_DELETED",
  MATERIAL_DELETED: "MATERIAL_DELETED",
  ALL_MATERIALS_DELETED: "ALL_MATERIALS_DELETED",
  INVOICE_SENT: "INVOICE_SENT",
  ALL_INVOICES_DELETED: "ALL_INVOICES_DELETED",
  REPORT_DELETED: "REPORT_DELETED",
};
