module.exports = {
  ESTIMATE_NOT_FOUND: "ESTIMATE_NOT_FOUND",
  ESTIMATE_NOT_APPROVED: "ESTIMATE_NOT_APPROVED",
  QUOTE_ALREADY_EXISTS: "QUOTE_ALREADY_EXISTS",
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  // Adaugă la obiectul existent
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  QUOTE_NOT_APPROVED: "QUOTE_NOT_APPROVED",
};
